import { StyleSheet } from 'react-native';

const Theme = StyleSheet.create({
    Container: {
        flex: 1,
        backgroundColor: '#ffffff',
        justifyContent: 'flex-start',
        marginTop: 10,
    },
    Fundo: {
        flex: 4,
        margin: 10,
        backgroundColor: '#ebe4d4',
        borderRadius: 10,
    },
    FundoMaior: {
        flex: 7,
        margin: 10,
        backgroundColor: '#ebe4d4',
        borderRadius: 10,
    },
    Foto: {
        width: 90,
        height: 120,
        backgroundColor: '#ffffff',
        borderStyle: 'solid',
        borderWidth: 1,
        borderColor: '#ee2d2d',
    },
    BotaoVermelho: {
        marginLeft: 10,
        marginRight: 10,
        marginBottom: 10,
        justifyContent: 'center',
        fontSize: 20,
        color: '#000000',
        backgroundColor: '#8e1414',
        borderColor: '#ee2d2d',
        borderStyle: 'solid',
        borderWidth: 1,
        height: 50,
        shadowColor: '#000000',
        shadowOffset: {width: 2, height: 1},
        shadowRadius: 3.84,
        shadowOpacity: 0.25,
        elevation: 3,
    },
    BotaoPadrao: {
        marginLeft: 10,
        marginRight: 10,
        marginBottom: 10,
        justifyContent: 'center',        
        fontSize: 20,
        color: '#ff0000',
        backgroundColor: '#f6e9e9',
        borderColor: '#ee2d2d',
        borderStyle: 'solid',
        borderWidth: 1,
        height: 50,
        shadowColor: '#000000',
        shadowOffset: {width: 2, height: 1},
        shadowRadius: 3.84,
        shadowOpacity: 0.25,
        elevation: 3,
    },
    TextoBotaoVermelho: {
        color: '#ffffff',
        textAlign: 'center',
        fontWeight: 'bold',
    },    
    TextoBotaoPadrao: {
        color: '#ee2d2d',
        textAlign: 'center',
        fontWeight: 'bold',
        alignItems: 'center',
    },
    Campo: {
        borderStyle: 'solid',
        borderWidth: 1,
        borderColor: '#ee2d2d',
        backgroundColor: '#ffffff',
        marginTop: 10,
        marginLeft: 15,
        marginRight: 15,
        paddingLeft: 15,
    },
    Rodape: {
        flex: 1,
        justifyContent: 'flex-end',
        marginBottom: 10,
    },
});

export default Theme;
